### PR TITLE
[Feature] Make Cart Page Responsive

### PR DESCRIPTION
**Pull request by oreoluwade**
#### What does this PR do?
- Makes the cart page responsive on all viewports

#### How should this be manually tested?
- Check out into the `feature/make-cart-page-responsive-167378368` branch
- Navigate to the cart page
- Check for responsiveness on all viewports

#### What are the relevant pivotal tracker stories?
- [#167378368](https://www.pivotaltracker.com/story/show/167378368)

### CODE REVIEW

**Comment by fisayomi** [comment]
How do I remove item from the cart or add to the quantity of items in my cart on smaller viewports?

**Comment by oreoluwade** [comment]
> How do I remove item from the cart or add to the quantity of items in my cart on smaller viewports?

I flirted with the idea of `action` being the most important thing on smaller screens apart from the item name, but then again, I thought that the price could be useful. My thinking is that If the person wants to perform an action, he'd have to click on the item to go to the product page and add more to cart.

I am open to suggestions however. If you think the action is more useful that quantity, could change that. It's all about perspective. In the end, one or two of the table items won't show on extra small screens. :)

**Comment by fisayomi** [comment]
> > How do I remove item from the cart or add to the quantity of items in my cart on smaller viewports?
> 
> I flirted with the idea of `action` being the most important thing on smaller screens apart from the item name, but then again, I thought that the price could be useful. My thinking is that If the person wants to perform an action, he'd have to click on the item to go to the product page and add more to cart.
> 
> I am open to suggestions however. If you think the action is more useful that quantity, could change that. It's all about perspective. In the end, one or two of the table items won't show on extra small screens. :)

I get the point of addition, but what about removing from Cart?. It would seem i cannot remove from my cart on smaller vps

**Comment by oreoluwade** [comment]
> > > How do I remove item from the cart or add to the quantity of items in my cart on smaller viewports?
> > 
> > 
> > I flirted with the idea of `action` being the most important thing on smaller screens apart from the item name, but then again, I thought that the price could be useful. My thinking is that If the person wants to perform an action, he'd have to click on the item to go to the product page and add more to cart.
> > I am open to suggestions however. If you think the action is more useful that quantity, could change that. It's all about perspective. In the end, one or two of the table items won't show on extra small screens. :)
> 
> I get the point of addition, but what about removing from Cart?. It would seem i cannot remove from my cart on smaller vps

The buttons are cojoined. Also, at the moment, wondering if the fact that `remove` is just a minus sign won't be confusing, especially since if one has say 15 items of a particular product, said fellow will keep clicking on minus till it goes to zero, but they'd not know what is happening at that time. Now that I think of it, maybe a popover/modal should be coming into view for any cart item such that one can perform necessary actions on the item and see all possibilities on said modal. What do you think?

**Pull request merged**
